<?php

return '[
            {
                "domain": ".zhihu.com",
                "expirationDate": 1529714889,
                "hostOnly": false,
                "httpOnly": false,
                "name": "__utma",
                "path": "/",
                "secure": false,
                "session": false,
                "storeId": "0",
                "value": "51854390.437250990.1466642466.1466642466.1466642466.1",
                "id": 1
            },
            {
                "domain": ".zhihu.com",
                "expirationDate": 1466644689,
                "hostOnly": false,
                "httpOnly": false,
                "name": "__utmb",
                "path": "/",
                "secure": false,
                "session": false,
                "storeId": "0",
                "value": "51854390.13.8.1466642573585",
                "id": 2
            },
            {
                "domain": ".zhihu.com",
                "hostOnly": false,
                "httpOnly": false,
                "name": "__utmc",
                "path": "/",
                "secure": false,
                "session": true,
                "storeId": "0",
                "value": "51854390",
                "id": 3
            },
            {
                "domain": ".zhihu.com",
                "expirationDate": 1466643066,
                "hostOnly": false,
                "httpOnly": false,
                "name": "__utmt",
                "path": "/",
                "secure": false,
                "session": false,
                "storeId": "0",
                "value": "1",
                "id": 4
            },
            {
                "domain": ".zhihu.com",
                "expirationDate": 1529714889,
                "hostOnly": false,
                "httpOnly": false,
                "name": "__utmv",
                "path": "/",
                "secure": false,
                "session": false,
                "storeId": "0",
                "value": "51854390.100--|2=registration_date=20160131=1^3=entry_date=20160131=1",
                "id": 5
            },
            {
                "domain": ".zhihu.com",
                "expirationDate": 1482410889,
                "hostOnly": false,
                "httpOnly": false,
                "name": "__utmz",
                "path": "/",
                "secure": false,
                "session": false,
                "storeId": "0",
                "value": "51854390.1466642466.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic",
                "id": 6
            },
            {
                "domain": ".zhihu.com",
                "expirationDate": 1529634189,
                "hostOnly": false,
                "httpOnly": false,
                "name": "_zap",
                "path": "/",
                "secure": false,
                "session": false,
                "storeId": "0",
                "value": "d099074d-b768-4d89-8dc4-1ed604fbae81",
                "id": 7
            },
            {
                "domain": ".zhihu.com",
                "expirationDate": 1469154215.126784,
                "hostOnly": false,
                "httpOnly": false,
                "name": "a_t",
                "path": "/",
                "secure": true,
                "session": false,
                "storeId": "0",
                "value": "\"2.0ABAKkS6fZQkXAAAAwMORVwAQCpEun2UJAAAAZXCOHQoXAAAAYQJVTaKDkVcAs0iW6XFoXbvBVm-A5efq2zL9Oj-fJz8vjkDa7LHPXq2c0Nm4dA_gaA==\"",
                "id": 8
            },
            {
                "domain": ".zhihu.com",
                "expirationDate": 1469154190.756395,
                "hostOnly": false,
                "httpOnly": false,
                "name": "cap_id",
                "path": "/",
                "secure": false,
                "session": false,
                "storeId": "0",
                "value": "\"ZTE5YWUzYjVkZTAwNDg3NWE1ODk0NGM0ZmUzN2RkYjQ=|1466562187|8f2d5199e713c8ef61ae919daca66ec928e38008\"",
                "id": 9
            },
            {
                "domain": ".zhihu.com",
                "expirationDate": 1561170192.395168,
                "hostOnly": false,
                "httpOnly": false,
                "name": "d_c0",
                "path": "/",
                "secure": false,
                "session": false,
                "storeId": "0",
                "value": "\"AAAAZXCOHQqPTsM14o_2_2dqO3sGcdPPYuo=|1466562188\"",
                "id": 10
            },
            {
                "domain": ".zhihu.com",
                "expirationDate": 1469154190.756359,
                "hostOnly": false,
                "httpOnly": false,
                "name": "l_cap_id",
                "path": "/",
                "secure": false,
                "session": false,
                "storeId": "0",
                "value": "\"ZGM3ZmMyOTlmZjYxNGRkMWI5MTQzMzJlZWJlOTNjYzk=|1466562187|25b1614b998e3c1353c0b85afd80cb75da99d67e\"",
                "id": 11
            },
            {
                "domain": ".zhihu.com",
                "expirationDate": 1469154213.043638,
                "hostOnly": false,
                "httpOnly": false,
                "name": "login",
                "path": "/",
                "secure": false,
                "session": false,
                "storeId": "0",
                "value": "\"ZDdhOTMyMGY3MTFlNDU3M2FjMmM2M2FhYjFjZWJjOGY=|1466562209|060b806940a5709c91555b7eedd41fc1de44ee95\"",
                "id": 12
            },
            {
                "domain": ".zhihu.com",
                "hostOnly": false,
                "httpOnly": false,
                "name": "n_c",
                "path": "/",
                "secure": false,
                "session": true,
                "storeId": "0",
                "value": "1",
                "id": 13
            },
            {
                "domain": ".zhihu.com",
                "expirationDate": 1561170190.756269,
                "hostOnly": false,
                "httpOnly": false,
                "name": "q_c1",
                "path": "/",
                "secure": false,
                "session": false,
                "storeId": "0",
                "value": "7a87de9d60334cd5a006bddb8d013034|1466562187000|1466562187000",
                "id": 14
            },
            {
                "domain": ".zhihu.com",
                "expirationDate": 1469154214.043727,
                "hostOnly": false,
                "httpOnly": true,
                "name": "z_c0",
                "path": "/",
                "secure": false,
                "session": false,
                "storeId": "0",
                "value": "Mi4wQUJBS2tTNmZaUWtBQUFCbGNJNGRDaGNBQUFCaEFsVk5vb09SVndDelNKYnBjV2hkdThGV2I0RGw1LXJiTXYwNlB3|1466562210|84fbea4af1cc1092828e592d0529162b7e7e9949",
                "id": 15
            },
            {
                "domain": "www.zhihu.com",
                "hostOnly": true,
                "httpOnly": false,
                "name": "_xsrf",
                "path": "/",
                "secure": false,
                "session": true,
                "storeId": "0",
                "value": "c525955a2a06f02eec0c2a484c907e86",
                "id": 16
            },
            {
                "domain": "www.zhihu.com",
                "expirationDate": 1529634189,
                "hostOnly": true,
                "httpOnly": false,
                "name": "_za",
                "path": "/",
                "secure": false,
                "session": false,
                "storeId": "0",
                "value": "e6745b34-4bee-4210-8cc3-f4b1399ef4f7",
                "id": 17
            },
            {
                "domain": "www.zhihu.com",
                "hostOnly": true,
                "httpOnly": false,
                "name": "s-i",
                "path": "/",
                "secure": false,
                "session": true,
                "storeId": "0",
                "value": "1",
                "id": 18
            },
            {
                "domain": "www.zhihu.com",
                "hostOnly": true,
                "httpOnly": false,
                "name": "s-q",
                "path": "/",
                "secure": false,
                "session": true,
                "storeId": "0",
                "value": "shujuwajue",
                "id": 19
            },
            {
                "domain": "www.zhihu.com",
                "hostOnly": true,
                "httpOnly": false,
                "name": "s-t",
                "path": "/",
                "secure": false,
                "session": true,
                "storeId": "0",
                "value": "autocomplete",
                "id": 20
            },
            {
                "domain": "www.zhihu.com",
                "hostOnly": true,
                "httpOnly": false,
                "name": "sid",
                "path": "/",
                "secure": false,
                "session": true,
                "storeId": "0",
                "value": "basaqirg",
                "id": 21
            }
    ]';
